### ISSUE TITLE
Consider switching to require('react')

### ISSUE THREAD

**Issue by cloudkite** [vslinko/babel-plugin-react-require#10]
> TLDR;
If we output `var React = require('React')` instead of `import React from 'react'` we don't have to worry about plugin order. Happy to make a PR if you think its a good idea.

I recently ran into an issue with `react-require` being applied after `transform-es2015-modules-commonjs`. The following babelrc runs fine when there is no matching env. However when I'm running with NODE_ENV=test `react-require` seems to be applied last by babel

my babelrc
```
{
  "presets": [
    ["es2015", { "loose": true, "modules": false }],
    "stage-2",
    "react"
  ],
  "plugins": [
    "transform-runtime",
    "react-require"
  ],
  "env": {
    "test": {
      "presets": [
        "es2015",
        "stage-2",
        "react"
      ]
    }
  }
}
```

any objections to switching to require('react')?

**Comment by cloudkite** [comment]
On second thoughts I guess this would break for users who want to transform import to something other than commonjs

**Comment by vslinko** [comment]
@cloudkite You're right, it's better to keep `import`.
The reason why I'm using `import` is because `import` is standard and `require` is not.

Is it possible to find out that `react-require` is evaluated after `transform-es2015-modules-commonjs` at runtime and print warning?

**Comment by cloudkite** [comment]
@vslinko that might get annoying when using the upcoming webpack 2 (like in above example babelrc)

as in this case you don't want babel transform imports at all and leave it for webpack to deal with

**Comment by gunnx** [comment]
@cloudkite How did you fix this? Running into same issue, I'm using Jest which doesn't use webpack so can't do the transform there.

**Comment by cloudkite** [comment]
@gunnx we changed our .babelrc to the following

```
{
  "presets": [
    ["es2015", {"modules": false}],
    "stage-2",
    "react"
  ],
  "plugins": [
    "react-require"
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    }
  }
}
```

**Comment by gunnx** [comment]
@cloudkite Yes I had use env test to redefine presets, we also have the issue that we are trying to compile code to run in Node environment
