### ISSUE TITLE
Add support for Component, PureComponent and PropTypes

### ISSUE THREAD

**Issue by giuseppeg** [vslinko/babel-plugin-react-require#13]
hi this plugin is very handy! Would you be interested in adding automatic requires for Component, PureComponent and PropTypes?

Detection is very trivial, I can put a PR together if you want.

**Comment by vslinko** [comment]
Hello. Thank you for your feedback!

I don't think that the plugin should require anything but React.createElement because it will not be so obvious for developers.

**Comment by giuseppeg** [comment]
fair enough I just asked because I prefer 
```js
import React, {Component, PropTypes} from 'react'

export default class extends Component {
 // ...
}
```
to `extends React.Component`

**Comment by nuclearspike** [comment]
I frequently do exactly the import that @giuseppeg gives in his example. The problem will be with my IDE because it will not know those have been imported and would show them as errors and no code completion. I'd almost prefer this as an IDE plugin and just have the import added to the file.

**Comment by vslinko** [comment]
Sorry, but I still don't want to add this feature to the plugin.

You can use webpack's [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/) to do implicit imports.
