### ISSUE TITLE
Recommended way to use this with typescript

### ISSUE THREAD

**Issue by emattias** [vslinko/babel-plugin-react-require#22]
Is there one? :)

**Comment by vslinko** [comment]
Hello.

I think it would be really complicated.

The easiest way that I can imagine is defining React as global variable in typings and using this plugin after tsc compiler.

**Comment by jeremejevs** [comment]
It's fairly simple, but yes, convoluted.

I personally prefer to use Babel for 100% of transpilation (warning: [not all TS features are supported](https://babeljs.io/docs/en/babel-plugin-transform-typescript)) and [`fork-ts-checker-webpack-plugin`](https://github.com/Realytics/fork-ts-checker-webpack-plugin) for type-checking (or `tsc --noEmit` outside of Webpack). Use `"jsx": "preserve"` to get TS to cooperate, no extra typings needed.

Alternatively, you could also have Babel as a second transpilation step after TypeScript, but that's noticeably less performant in most scenarios.
