### ISSUE TITLE
Not compatible with babel6

### ISSUE THREAD

**Issue by pgilad** [vslinko/babel-plugin-react-require#6]
Seems to be broken with Babel6, getting an error:
```
  return new babel.Transformer('react-require', plugin)
         ^

TypeError: babel.Transformer is not a function
```

**Comment by existentialism** [comment]
@pgilad I started working on a PR (https://github.com/existentialism/babel-plugin-react-require/tree/babel6), seems to be working in my local tests, will continue testing a bit on some larger projects.

**Comment by pgilad** [comment]
:+1: Awesome!

**Comment by kombucha** [comment]
I would also be interested in this :+1:

**Comment by vslinko** [comment]
If you're using webpack you could replace this plugin by webpack's [ProvidePlugin](http://webpack.github.io/docs/list-of-plugins.html#provideplugin):

```js
new webpack.ProvidePlugin({
    React: 'react'
})
```

**Comment by just-boris** [comment]
6 version of Babel has changed PluginAPI: http://babeljs.io/blog/2015/10/29/6.0.0/#plugin-api

Issue can be solved with little changed around plugin call. See example in the article from link.

@existentialism I viewed your changes, good job, send it to us

**Comment by vslinko** [comment]
@existentialism Yes, we're waiting for your PR. :rocket:

**Comment by vslinko** [comment]
Closed by https://github.com/vslinko/babel-plugin-react-require/pull/7
