### ISSUE TITLE
Consider adding support for Node.js v0.12

### ISSUE THREAD

**Issue by martinandert** [vslinko/babel-plugin-react-require#8]
The output generated by Babel in the lib directory contains ES2015 syntax like `let`, `const` and shorthand properties, which Node v0.12 doesn't understand.

Please consider adding `transform-es2015-shorthand-properties` and `transform-es2015-block-scoping` to .babelrc.

**Comment by vslinko** [comment]
Closed by https://github.com/vslinko/babel-plugin-react-require/commit/b11d650a4d8e9d3699784492eaad979c7ddd9b2b

Trank you for your contribution.
