### ISSUE TITLE
Mention that plugin generates ES6 code

### ISSUE THREAD

**Issue by FredyC** [vslinko/babel-plugin-react-require#9]
If plugin is added last to the list of plugins, then babel doesn't transform it and leaves `import React from 'react';` code in there which than fails. Might be worth mentioning in docs that this plugin should be among the first ones or even before `es2015` preset if used.

**Comment by vslinko** [comment]
Readme updated. Please check it out.

**Comment by FredyC** [comment]
Looks great to me, thanks.
